/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package luolapako;

import java.awt.Color;

/**
 *
 * @author Toni
 */
public class LuolaPakoUI extends javax.swing.JFrame {

    /**
     * Creates new form LuolaPakoUI
     */
    public LuolaPakoUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        luolaLista = new javax.swing.JList();
        Ratkaise = new javax.swing.JButton();
        kuvaKentta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 800));

        luolaLista.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Luola 1", "Luola 2" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        luolaLista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        luolaLista.setToolTipText("");
        luolaLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                luolaListaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(luolaLista);

        Ratkaise.setText("Ratkaise");
        Ratkaise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RatkaiseMouseClicked(evt);
            }
        });

        kuvaKentta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/luolapako/luola0.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Ratkaise)
                        .addGap(119, 119, 119)
                        .addComponent(kuvaKentta, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ratkaise)
                .addGap(51, 51, 51)
                .addComponent(kuvaKentta, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 439, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void luolaListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_luolaListaMouseClicked

        // TODO add your handling code here:

        kuvaKentta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/luolapako/luola" + luolaLista.getAnchorSelectionIndex() + ".jpg")));

    }//GEN-LAST:event_luolaListaMouseClicked

    private void RatkaiseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RatkaiseMouseClicked
        // TODO add your handling code here:
        LuolaPako.ratkaise("C:/Users/Toni/Documents/LuolaPako/src/luolapako/luola" + luolaLista.getAnchorSelectionIndex() + ".jpg");
    }//GEN-LAST:event_RatkaiseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LuolaPakoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LuolaPakoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LuolaPakoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LuolaPakoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LuolaPakoUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ratkaise;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kuvaKentta;
    private javax.swing.JList luolaLista;
    // End of variables declaration//GEN-END:variables
}
